use_frameworks!

platform :ios, '13.0'

target 'PinOnMobile-lib_Example' do
  pod 'PinOnMobile-lib', :path => '../'
  pod 'Alamofire','5.5.0'
  pod 'SwiftyRSA', '1.5.0'
  pod 'CryptoSwift', '1.0.0'
  pod 'PercentEncoder','1.2.1'
  pod 'CocoaMQTT','1.2.5'
  pod 'Eureka','~> 5.4'


  target 'PinOnMobile-lib_Tests' do
    inherit! :search_paths

    
  end
end
